openapi: 3.0.0
info:
  title: Diary API
  description: A simple diary API with basic authentication
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:3000
    description: Local development server

tags:
  - name: Authentication
    description: User authentication endpoints
  - name: Diary Entries
    description: Manage diary entries

paths:
  $ref: './paths/auth.yaml'
  $ref: './paths/diary.yaml'

components:
  $ref: './components.yaml'